apiVersion: v1
kind: Service
metadata:
  name: stripe-checkout-service
spec:
  selector:
    app: stripe-checkout-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 4242
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-checkout-app
spec:
  selector:
    matchLabels:
      app: stripe-checkout-app
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stripe-checkout-app
    spec:
      containers:
      - name: stripe-checkout-app
        image: arnobdev/stripe-checkout
        imagePullPolicy: Always
        ports:
          - containerPort: 4242
        resources:
          limits:
            cpu: 80m
            memory: 80Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: regcred 
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stripe-checkout-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: stripe-checkout.32-1.xyz
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
            service:
               name: stripe-checkout-service
               port:
                  number: 80