version: '3'

services:
  s3_storage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    restart: always    
    networks:
      - backend
  
networks:
  backend:    
    driver: bridge